site_draft:
  id: ehf-egovernment-g1-draft
  type: site
  path: target/site
  properties:
    domain: anskaffelser.dev
    path: egovernment/g1/spec/draft

site_current:
  mode: release
  id: ehf-egovernment-g1-current
  type: site
  path: target/site
  properties:
    domain: anskaffelser.dev
    path: egovernment/g1/spec/current